### ISSUE TITLE
Kinetic対応

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/navigation#7]
https://github.com/open-rdc/orne_navigation/issues/261 に関連して，こちらのレポジトリもKineticに対応する必要がある

* 具体的な作業
- [x]  kinetic-devel のamclに膨張リセットを適用する

**Comment by Hiroki-Goto** [comment]
実機での挙動確認も行った

**Comment by Nasupl** [comment]
@Hiroki-Goto PR立てましょうね
